# Generated by Django 2.2.4 on 2019-08-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20190815_1039'),
        ('perfil', '0002_auto_20190814_2352'),
    ]

    operations = [
    ]
