# Generated by Django 2.2.4 on 2019-08-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20190814_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
