# Generated by Django 2.2.4 on 2019-08-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20190815_1026'),
        ('produto', '0005_auto_20190815_1042'),
    ]

    operations = [
    ]
